# This file defines how the Google App Engine runs this app
runtime: python39

handlers:
  # This configures Google App Engine to serve the index.html as /
  # This is deliberately not in the static folder, to keep the URL of the main page shorter
- url: /
  static_files: index.html
  upload: index.html

  # This configures Google App Engine to serve the files in the app's static directory.
- url: /static
  static_dir: static

  # This handler routes all requests not caught above to the Flask app
- url: /.*
  script: auto