[package]
name = "sanctuary-player-android"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
name = "sanctuary_player_android"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
sanctuary-player-app = { path = "../app" }
log.workspace = true

[target.'cfg(target_os = "android")'.dependencies]
oxideav-mediacodec.workspace = true
ash = "0.38"
jni = "0.22.4"
android-activity = { version = "0.6.1", features = ["game-activity"] }
egui.workspace = true
egui-wgpu.workspace = true
ndk = { version = "0.9.0", default-features = false, features = ["rwh_06"] }
pollster.workspace = true
raw-window-handle = "0.6.2"
wgpu.workspace = true

[package.metadata.android]
package = "app.sanctuaryplayer.android"
build_targets = ["aarch64-linux-android"]

[[package.metadata.android.uses_permission]]
name = "android.permission.INTERNET"

[package.metadata.android.application]
label = "Sanctuary Player"

[[package.metadata.android.application.activity]]
name = "com.google.androidgamesdk.GameActivity"
exported = true
config_changes = "allKnown"

[[package.metadata.android.application.activity.meta_data]]
name = "android.app.lib_name"
value = "sanctuary_player_android"

[[package.metadata.android.application.activity.intent_filter]]
actions = ["android.intent.action.MAIN"]
categories = ["android.intent.category.LAUNCHER"]
